version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-aws-terra
    volumes:
      - postgres_data:/data/db

  authors-ms:
    build:
      context: .
      dockerfile: ./deployments/docker/authors/Dockerfile
    volumes:
      - ./cmd/authors-ms:/go/src/go-aws-terra/cmd/authors-ms
    ports:
      - "15000:80" 

  send-telegram-message:
    build:
      context: .
      dockerfile: ./deployments/docker/telegram/Dockerfile
    volumes:
      - ./cmd/send-telegram-message:/go/src/go-aws-terra/cmd/send-telegram-message
    ports:
      - "15001:80" 

volumes:
  postgres_data:

