version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.1.0

parameters:
  run-authors-ms-workflow:
    type: boolean
    default: true
  run-send-telegram-message-workflow:
    type: boolean
    default: false

jobs:
  go-aws-terra-author-ms-image-build-push:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Author Microservice Image Build And Push
          command: |
            export IMAGE_NAME=$ECR_REPO_URL/go-aws-terra-image-repo/author-ms:$CIRCLE_SHA1

            aws configure set default.region us-east-1
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_URL

            docker build -f ./deployments/docker/authors/Dockerfile -t $IMAGE_NAME .

            docker push $IMAGE_NAME
  go-aws-terra-send-telegram-message-image-build-push:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Send Telegram Message Microservice Image Build And Push
          command: |
            export IMAGE_NAME=$ECR_REPO_URL/go-aws-terra-image-repo/send-telegram-message:$CIRCLE_SHA1

            aws configure set default.region us-east-1
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_URL

            docker build -f ./deployments/docker/telegram/Dockerfile -t $IMAGE_NAME .

            docker push $IMAGE_NAME

workflows:
  go-aws-terra-author-ms-workflows:
    when:
      or:
        - << pipeline.parameters.run-authors-ms-workflow >>
    jobs:
      - go-aws-terra-author-ms-image-build-push:
          filters:
            branches:
              only: master
  go-aws-terra-send-telegram-message-workflows:
    when:
      or:
        - << pipeline.parameters.run-send-telegram-message-workflow >>
    jobs:
      - go-aws-terra-send-telegram-message-image-build-push:
          filters:
            branches:
              only: master
