---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authors-ms
spesc:
  selector:
    app: authors-ms
  ports:
    - protocol: "TCP"
      port: 15000
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-ms
  labels:
    app: authors-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authors-ms
  template:
    metadata:
      labels:
        app: authors-ms
    spec:
      containers:
        - name: container-author-ms
          image: $ECR_AUTHORS_REPO_URL:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authors-ms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authors-ms
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
