---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: send-telegram-message
spesc:
  selector:
    app: send-telegram-message
  ports:
    - protocol: "TCP"
      port: 15001
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-telegram-message
  labels:
    app: send-telegram-message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-telegram-message
  template:
    metadata:
      labels:
        app: send-telegram-message
    spec:
      containers:
        - name: container-send-telegram-message
          image: $ECR_TELEGRAM_REPO_URL:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authors-ms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: send-telegram-message
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
